CREATE TABLE "system_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "system_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ollama_manager_enabled" boolean DEFAULT false NOT NULL,
	"ollama_base_url" text DEFAULT 'http://localhost:11434/' NOT NULL
);
